import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/app/providers";
import Navbar from "@/components/Navbar";

import { Flex, Box } from "@chakra-ui/react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <Flex direction="column" minH="100vh">
            {/* Fixed height Navbar */}
            <Box as="header">
              {/* <Navbar /> */}
            </Box>

            {/* Children should grow and fill remaining space */}
            <Box as="main" flex="1" overflow="">
              {children}
            </Box>
          </Flex>
        </Provider>
      </body>
    </html>
  );
}
